create table gallery
(
    id          int auto_increment
        primary key,
    name        varchar(255) null,
    image       varchar(255) null,
    type        varchar(255) null,
    size        varchar(255) null,
    description text         null,
    status      varchar(100) null,
    price       int          null
);

create table payments
(
    id           int auto_increment
        primary key,
    art_id       int                            not null,
    email        varchar(255)                   not null,
    name         varchar(255)                   not null,
    phone        varchar(30)                    not null,
    address      varchar(255)                   not null,
    message      text                           null,
    status       varchar(255) default 'created' null,
    hash         varchar(255)                   null,
    payment_data json                           null
);

INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (27, 'Enigma', 'c3.png', 'OIL ON CANVAS', '60 cm', 'At the center of the composition stands a mysterious figure, partially obscured by a beige rectangle, possibly added to preserve secrecy or privacy. Surrounding this central figure is a whole world of mythological and classical characters. Muscular human forms and possibly deities, immersed in dynamic poses, create a sense of movement and energy.', 'available', 900);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (24, 'Moment', 'w2.png', 'OIL ON CANVAS', '120 x 80 x 1 D cm', 'Each raindrop is a metaphor for a feeling that cannot be expressed. She gazes into the distance, but her eyes do not penetrate through the window. Her gaze is not directed outside, but inward—into the space of her own consciousness. The blue tones and soft light create an atmosphere of melancholy and solitude. The car, perhaps, is not just a vehicle, but a symbol of a journey through memories and reflections. Despite the glass separating her from the outside world, her image remains clear and strong, highlighting the depth and complexity of her inner state.', 'available', 900);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (22, 'Swimmer', 'w4.jpg', 'OIL ON CANVAS', '155 х 105 х 1 D cm', 'In the silence of the evening twilight, as the last rays of the sun touch the surface of the water, a mysterious figure emerges, submerged in the watery depths. Only the upper part of the body and hands are visible above the surface, as if striving to break free from the embrace of the water. Light patterns playing on the water create a whimsical interplay of light and shadow, giving the painting a mystical depth and enigma.', 'available', 2200);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (25, 'Wild', 'c1.png', 'OIL ON CANVAS', '60 cm', 'The central figure is the head of a leopard, symbolizing the primal power hidden within every living being. Its eyes are full of wisdom and instinct, piercing through space as if opening a doorway to the natural world. Around it unfolds a whirlwind of fantasies: images of horses, snakes, and human faces intertwine into a harmonious whole, symbolizing the interconnectedness of all forms of life. Every detail here is not just part of the background, but something alive, significant, as if everything is coming to life in a unified flow of existence. The snakes and their patterns point to wisdom and hidden danger, while the human figures perhaps reflect the spiritual essence within the context of nature.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (26, 'Child of Mystery', 'c2.png', 'OIL ON CANVAS', '50 cm', 'The circular format of the canvas symbolizes the continuity and cyclic nature of life. I used cool shades of blue and green to create an atmosphere of calm and fluidity, reflecting the inner world of a person. The figures in motion embody energy and vitality, while the geometric shapes resembling shields add an element of mystery and protection. The interaction between abstract elements and human figures emphasizes the harmony between humans and the surrounding world, striving for unity and understanding.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (29, 'Fusion', 'c6.png', 'OIL ON CANVAS', '50 cm', 'The composition features images of leaves, flowers, and possibly marine creatures, interwoven in a smooth and organic manner. The color palette includes cool shades of blue, green, and purple, creating a sense of tranquility and harmony.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (28, 'Creation', 'c7.png', 'OIL ON CANVAS', '50 cm', 'The painting conveys a sense of movement and energy, with elements seemingly merging into one another, creating a harmonious and vibrant canvas. This artwork invites the viewer to immerse themselves in a world of fantasies and interpretations, where each person can see something unique and feel a connection to nature and its endless motion.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (23, 'Alice', 'w1.png', 'OIL ON CANVAS', '160 x 60 x 1 D cm', 'The woman gazes through a window covered in raindrops, as if her thoughts and emotions are also drops—sliding down the glass, unable to escape.The raindrops seem to divide her from the outside world. They create a barrier that distorts and blurs her features, reminding us of how often our own feelings, fears, and dreams become hazy and impenetrable to others. Her gaze is not directed at us, but inward, beyond reflections and memories. It is filled with an indescribable calm, yet it carries the depth of untold stories.', 'available', 7000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (19, 'Horse #3', 'horse3.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'This captivating painting of a horse\'s profile is a stunning blend of realism and expressive color. The deep, rich tones of the horse’s coat are beautifully contrasted against the dark background, creating a dramatic and intense focus on the animal’s powerful form. The subtle highlights of red and orange bring warmth and movement to the image, suggesting energy and strength beneath the surface. The horse’s posture, dignified and calm, exudes a sense of nobility and control, making this piece perfect for those who appreciate the beauty and grace of equestrian art. It’s a striking statement piece that would elevate any space with its dynamic presence.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (17, 'The Wind', 'wind.jpg', 'OIL ON CANVAS', '100 x 73 x 1 D cm', 'This delicate painting, rendered in soft, flowing shades of blue and green, creates a dreamlike atmosphere, evoking a sense of fluidity and motion. Figures and animals seem to merge and dissolve into one another, symbolizing the interconnectedness of life and the blurred boundaries between human and nature. The use of transparent washes of color gives the work an ethereal, almost meditative quality, inviting the viewer to contemplate the transient and fleeting nature of existence. This piece would add a calming yet thought-provoking presence to any space, perfect for those who appreciate art that communicates both serenity and depth.', 'available', 1400);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (20, 'Horse #4', 'horse4.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'This dynamic painting of a horse captivates with its vibrant energy and rich color palette. The artist has masterfully captured the sheen of the horse\'s coat, using warm, fiery tones that seem to flicker across its muscular form. The deep reds and oranges create a sense of movement and power, while the horse’s calm, introspective gaze balances the intensity of the background. The dark, abstract setting contrasts beautifully with the glowing hues, making the horse the undeniable focal point. This painting would be a bold and powerful statement piece, ideal for those who appreciate the majestic strength and elegance of equine subjects.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (18, 'Horse #2', 'horse2.jpg', 'OIL ON CANVAS', '60 x 80 x 1 D cm', 'This elegant painting of a horse gently lowering its head conveys a sense of calm and grace. The soft sheen of the horse’s coat, meticulously rendered, highlights the artist’s attention to detail, bringing out the animal’s muscular form and the natural beauty of its movement. The light background contrasts beautifully with the warm, earthy tones of the horse, allowing it to stand out and draw the viewer’s focus to the tranquility and strength it embodies. This piece would make a serene and striking addition to any space, appealing to those who appreciate the subtleties of equestrian art and the majesty of horses.', 'available', 550);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (16, 'Mother', 'mother.jpg', 'OIL ON CANVAS', '90 x 72 x 1 D cm', 'This exquisite painting exudes timeless beauty and spiritual depth, capturing the serene tenderness of motherhood. The central figure, a mother cradling her child, evokes a sense of purity, love, and protection, with flowing lines that add warmth and intimacy to the scene. The soft golden tones create an ethereal atmosphere, reminiscent of classical religious icons, while the delicate lilies symbolize innocence and renewal. Every brushstroke feels deliberate, blending realism with abstraction, inviting quiet reflection on the sacredness of maternal love. This artwork would grace any space, bringing with it tranquility and contemplation, perfect for those seeking art with emotional and timeless resonance.', 'available', 1650);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (11, 'Adam & Eva', 'adamandeva.jpg', 'OIL and ACRYLIC ON CANVAS', '100 х 72 х 1 D cm', 'This painting blends classical biblical themes with modern artistic techniques. At the center, Adam and Eve stand nude, holding the apple—a symbol of temptation and original sin. Their figures are depicted in a realistic, Renaissance-like style, contrasting with the vibrant, abstract background of bold brushstrokes. Surrounding them are various faces and creatures, including a Christ-like figure in the upper left, an owl, and other mystical beings. These elements deepen the metaphorical narrative of temptation and consequence. Unexpectedly, a French bulldog sits in the bottom right, adding a surreal and contemporary touch. The piece feels like a fusion of time periods, exploring timeless themes through a multi-layered, visually complex composition.', 'available', 3000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (34, 'Heritage', 'veil.jpg', 'OIL ON CANVAS', '155 х 105', 'This painting combines a variety of symbols and figures, creating a complex and layered composition. In the foreground, we see a saintly figure with a halo, possibly referencing religious or spiritual themes. Cupid with his bow and arrow introduces elements of romance or destiny, while the presence of animals—a bull with grand horns and ornate decoration, along with flying birds—symbolizes natural forces, power, and freedom.', 'available', 7000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (12, 'Yellow Spain', 'yellowspain.jpg', 'OIL ON CANVAS', '60 cm', 'This painting depicts two colorful birds perched on a branch amidst bright yellow lemons and lush greenery. The birds, with their striking blue and black plumage, stand out against the vibrant backdrop. The circular composition is framed by delicate blue ornamental patterns, adding an elegant touch. The combination of the vivid fruit, foliage, and birds creates a harmonious, lively scene that feels both natural and decorative, evoking a sense of Mediterranean warmth and beauty.', 'available', 850);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (2, 'Merlyn', '2.jpg', 'OIL ON CANVAS', '160 х 110 х 1 D cm', 'This painting evokes a deep emotional response by blending human fragility with visual abstraction. The face, while realistic, appears fragmented and distorted, resembling a crumpled surface. This could symbolize the fragility of identity, the layers of emotional experiences, or the pressures of societal expectations. The wide, expressive eyes draw attention to the inner depth of the figure, creating a sense of vulnerability. The crumpled texture might also represent life\'s hardships or the scars that shape our identity over time. The overall impression is one of beauty intertwined with imperfection, capturing the complexities of the human condition.', 'in private collection', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (13, 'Andalusian Dream', 'adream.jpg', 'OIL and SPRAY ON CANVAS', '100 x 80 x 1 D cm', 'This painting exudes a dreamlike quality, blending religious and cultural symbolism. The central figure appears to be a serene Madonna holding a child, reminiscent of classical Christian iconography. Around her, other figures and symbols emerge softly, as if from a hazy memory. The prominent white flowers, possibly magnolias, add a sense of purity and grace, contrasting with the earth-toned palette. A man in the lower left corner smokes a cigar, dressed in what looks like traditional attire, bringing an element of modernity and cultural identity to the composition. A heart held by one of the figures on the right could symbolize deep emotional or spiritual significance. The painting mixes fluid brushstrokes with more defined forms, creating a layered, atmospheric effect, invoking themes of faith, memory, and identity. The overall composition feels introspective, inviting the viewer to reflect on the juxtaposition of tradition and personal experience.', 'available', 1650);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (32, 'Hope', 'cl2.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting is filled with subtle symbolism and a sense of incompleteness. At the center of the composition is a golden hand, raised in a gesture that can be interpreted as a sign of approval, control, or inner harmony. The metallic texture of the hand gives it an artificial yet majestic quality, as if it were part of an ancient statue or artifact possessing special power.', 'in private collection', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (31, 'Open', 'cl1.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting masterfully balances contrasts and symbolism. The artist draws attention to the golden hand, illuminated against a dark, abstract backdrop. The hand feels more than just a physical object — it suggests power, control, or inner strength. Its detailed, elegant lines, highlighted by light, sharply contrast with the blurred, abstract background, evoking tension and mystery.', 'sold', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (33, 'Gate', 'cl3.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting represents a combination of realism and abstraction. The central element of the composition is a hand extended forward, holding an unusual object that resembles a stylized pomegranate or flower. The hand is depicted in a highly realistic manner, with attention to light and shadow, emphasizing its three-dimensionality and texture. Surrounding the hand are abstract, broad brushstrokes in various shades of brown, beige, and black, creating a sense of movement and adding dynamism. These strokes give the painting a modern, expressive quality.', 'available', 1500);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (30, 'Observer', 'd1.png', 'OIL ON CANVAS', '140 x 90 x 1 D cm', 'This painting represents a modern take on the classics, where the ancient ideal of beauty, symbolized by Michelangelo\'s statue of David, is intertwined with vibrant elements of contemporary art and abstraction. The figure of David, embodying timeless values of masculine strength and beauty, is set against a backdrop of dynamic strokes in bright, almost neon colors—green, blue, and purple—that break the monumentality of the sculpture, creating a contrast with the idealized body. The right side of the composition is filled with a profusion of flowers, where realistically rendered petals and leaves seem to reach into the space of the sculpture. This floral motif symbolizes life, growth, and the transience of nature, compared to the cold immobility of marble. The artwork establishes a dialogue between the past and the present: the timeless beauty of classical sculpture and the modern art movements, driven by experimentation, saturation, and rethinking of conventions. It invites viewers to reflect on how our perceptions of beauty and art continue to evolve.', 'available', 4000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (14, 'Weekend in Spain', 'weekend.jpg', 'OIL and ACRYLIC ON CANVAS', '114 x 97 x 1 D cm', 'This painting, with its blend of classical and modern elements, seems to explore the interplay between mythology, history, and the subconscious. The figure holding a crescent moon and palm frond appears to reference classical or divine imagery, while other fragmented forms, like the bull and dancers, suggest themes of struggle, transformation, or rituals. The flowing lines and drips of paint evoke fluidity, symbolizing time’s passage and the blending of different epochs or ideas. The vibrant splashes of color contrast with the muted background, creating tension between chaos and order. Overall, the painting invites reflection on power, identity, and the cycles of human experience.', 'available', 3000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (21, 'Horse #5', 'horse5.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'This striking painting captures the majesty and grace of a horse in a beautifully expressive style. The artist\'s use of deep, rich colors brings the animal\'s muscular structure to life, while the subtle lighting accentuates the horse\'s glossy coat, creating a sense of movement and vitality. The red and black abstract background adds intensity and depth, evoking a feeling of raw power and elegance. The horse\'s attentive, alert expression conveys intelligence and strength, making this artwork an inspiring centerpiece for any equestrian lover or art collector. It would make a bold, yet refined statement in any room, blending emotion and mastery.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (15, 'Horse #1', 'horse1.jpg', 'OIL ON CANVAS', '200 x 145 x 1 D cm', 'This striking painting of a horse\'s head emerging from a dark background creates a powerful sense of mystery and depth. The horse\'s intense gaze, highlighted by the contrast between its polished, almost sculptural form and the obscured background, draws the viewer\'s attention. The darkness surrounding the horse symbolizes the unknown or perhaps the subconscious, while the detailed realism of the animal suggests strength, wisdom, or silent power. The minimalist approach focuses on the essence of the horse, evoking a deep connection with the animal\'s spirit and highlighting its raw, unspoken emotion.', 'available', 2000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (1, 'The destruction Painting', '1.jpg', 'OIL ON CANVAS', '130 W x 160 H x 1 D cm', 'This surreal painting blends dreamlike elements with symbolic imagery, creating a scene rich in hidden meaning. The woman in a yellow dress, standing amidst bizarre objects like a large wasp, shells, and an unconscious figure in a gas mask, suggests themes of environmental decay, danger, and human fragility. The Ferris wheel in the background contrasts with the dark symbols in the foreground, evoking a clash between innocence and the chaotic forces of nature. The maze symbolizes confusion or a search for meaning, while the pufferfish in the sky adds to the absurdity, portraying the unpredictable and fragile balance of life.', 'available', 5000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (4, 'Birth', '4.jpg', 'OIL ON CANVAS', '100 W x 80 H x 1 D cm', 'This vibrant painting of hummingbirds in flight captures the beauty of nature, symbolizing freedom, grace, and vitality. The hummingbirds, depicted in various positions and colors, represent diversity and the dynamism of life. Their hovering movement amidst lush green foliage evokes a sense of harmony between creatures and their environment. The contrast between the birds\' bright plumage and the deep, tranquil background may symbolize hope and vibrancy amid challenges or darker moments. The nest with eggs introduces a theme of creation, nurturing, and the cyclical nature of life, suggesting a delicate balance in the natural world.', 'sold in auction', 0);
