create table gallery
(
    id          int auto_increment
        primary key,
    name        varchar(255) null,
    image       varchar(255) null,
    type        varchar(255) null,
    size        varchar(255) null,
    description text         null,
    status      varchar(100) null,
    price       int          null
);

create table payments
(
    id           int auto_increment
        primary key,
    art_id       int                            not null,
    email        varchar(255)                   not null,
    name         varchar(255)                   not null,
    phone        varchar(30)                    not null,
    address      varchar(255)                   not null,
    message      text                           null,
    status       varchar(255) default 'created' null,
    hash         varchar(255)                   null,
    payment_data json                           null
);

INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (1, 'The destruction Painting', '1.jpg', 'OIL ON CANVAS', '130 W x 160 H x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 5000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (2, 'Merlyn', '2.jpg', 'OIL ON CANVAS', '160 х 110 х 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'in private collection', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (4, 'Birth', '4.jpg', 'OIL ON CANVAS', '100 W x 80 H x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'sold in auction', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (11, 'Adam & Eva', 'adamandeva.jpg', 'OIL and ACRYLIC ON CANVAS', '100 х 72 х 1 D cm', 'This painting blends classical biblical themes with modern artistic techniques. At the center, Adam and Eve stand nude, holding the apple—a symbol of temptation and original sin. Their figures are depicted in a realistic, Renaissance-like style, contrasting with the vibrant, abstract background of bold brushstrokes. Surrounding them are various faces and creatures, including a Christ-like figure in the upper left, an owl, and other mystical beings. These elements deepen the metaphorical narrative of temptation and consequence. Unexpectedly, a French bulldog sits in the bottom right, adding a surreal and contemporary touch. The piece feels like a fusion of time periods, exploring timeless themes through a multi-layered, visually complex composition.', 'available', 3000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (12, 'Yellow Spain', 'yellowspain.jpg', 'OIL ON CANVAS', '60 cm', 'This painting depicts two colorful birds perched on a branch amidst bright yellow lemons and lush greenery. The birds, with their striking blue and black plumage, stand out against the vibrant backdrop. The circular composition is framed by delicate blue ornamental patterns, adding an elegant touch. The combination of the vivid fruit, foliage, and birds creates a harmonious, lively scene that feels both natural and decorative, evoking a sense of Mediterranean warmth and beauty.', 'available', 850);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (13, 'Andalusian Dream', 'adream.jpg', 'OIL and SPRAY ON CANVAS', '100 x 80 x 1 D cm', 'This painting exudes a dreamlike quality, blending religious and cultural symbolism. The central figure appears to be a serene Madonna holding a child, reminiscent of classical Christian iconography. Around her, other figures and symbols emerge softly, as if from a hazy memory. The prominent white flowers, possibly magnolias, add a sense of purity and grace, contrasting with the earth-toned palette. A man in the lower left corner smokes a cigar, dressed in what looks like traditional attire, bringing an element of modernity and cultural identity to the composition. A heart held by one of the figures on the right could symbolize deep emotional or spiritual significance. The painting mixes fluid brushstrokes with more defined forms, creating a layered, atmospheric effect, invoking themes of faith, memory, and identity. The overall composition feels introspective, inviting the viewer to reflect on the juxtaposition of tradition and personal experience.', 'available', 1650);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (14, 'Weekend in Spain', 'weekend.jpg', 'OIL and ACRYLIC ON CANVAS', '114 x 97 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 3000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (15, 'Horse #1', 'horse1.jpg', 'OIL ON CANVAS', '200 x 145 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 2000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (16, 'Mother', 'mother.jpg', 'OIL ON CANVAS', '90 x 72 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 1650);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (17, 'The Wind', 'wind.jpg', 'OIL ON CANVAS', '100 x 73 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 1400);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (18, 'Horse #2', 'horse2.jpg', 'OIL ON CANVAS', '60 x 80 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 550);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (19, 'Horse #3', 'horse3.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (20, 'Horse #4', 'horse4.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (21, 'Horse #5', 'horse5.jpg', 'OIL ON CANVAS', '120 x 120 x 1 D cm', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 2300);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (22, 'Swimmer', 'w4.jpg', 'OIL ON CANVAS', '155 х 105 х 1 D cm', 'In the silence of the evening twilight, as the last rays of the sun touch the surface of the water, a mysterious figure emerges, submerged in the watery depths. Only the upper part of the body and hands are visible above the surface, as if striving to break free from the embrace of the water. Light patterns playing on the water create a whimsical interplay of light and shadow, giving the painting a mystical depth and enigma.', 'available', 2200);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (23, 'Alice', 'w1.png', 'OIL ON CANVAS', '160 x 60 x 1 D cm', 'The woman gazes through a window covered in raindrops, as if her thoughts and emotions are also drops—sliding down the glass, unable to escape.The raindrops seem to divide her from the outside world. They create a barrier that distorts and blurs her features, reminding us of how often our own feelings, fears, and dreams become hazy and impenetrable to others. Her gaze is not directed at us, but inward, beyond reflections and memories. It is filled with an indescribable calm, yet it carries the depth of untold stories.', 'available', 7000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (24, 'Moment', 'w2.png', 'OIL ON CANVAS', '120 x 80 x 1 D cm', 'Each raindrop is a metaphor for a feeling that cannot be expressed. She gazes into the distance, but her eyes do not penetrate through the window. Her gaze is not directed outside, but inward—into the space of her own consciousness. The blue tones and soft light create an atmosphere of melancholy and solitude. The car, perhaps, is not just a vehicle, but a symbol of a journey through memories and reflections. Despite the glass separating her from the outside world, her image remains clear and strong, highlighting the depth and complexity of her inner state.', 'available', 900);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (25, 'Wild', 'c1.png', 'OIL ON CANVAS', '60 cm', 'The central figure is the head of a leopard, symbolizing the primal power hidden within every living being. Its eyes are full of wisdom and instinct, piercing through space as if opening a doorway to the natural world. Around it unfolds a whirlwind of fantasies: images of horses, snakes, and human faces intertwine into a harmonious whole, symbolizing the interconnectedness of all forms of life. Every detail here is not just part of the background, but something alive, significant, as if everything is coming to life in a unified flow of existence. The snakes and their patterns point to wisdom and hidden danger, while the human figures perhaps reflect the spiritual essence within the context of nature.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (26, 'Child of Mystery', 'c2.png', 'OIL ON CANVAS', '50 cm', 'The circular format of the canvas symbolizes the continuity and cyclic nature of life. I used cool shades of blue and green to create an atmosphere of calm and fluidity, reflecting the inner world of a person. The figures in motion embody energy and vitality, while the geometric shapes resembling shields add an element of mystery and protection. The interaction between abstract elements and human figures emphasizes the harmony between humans and the surrounding world, striving for unity and understanding.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (27, 'Enigma', 'c3.png', 'OIL ON CANVAS', '60 cm', 'At the center of the composition stands a mysterious figure, partially obscured by a beige rectangle, possibly added to preserve secrecy or privacy. Surrounding this central figure is a whole world of mythological and classical characters. Muscular human forms and possibly deities, immersed in dynamic poses, create a sense of movement and energy.', 'available', 900);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (28, 'Creation', 'c7.png', 'OIL ON CANVAS', '50 cm', 'The painting conveys a sense of movement and energy, with elements seemingly merging into one another, creating a harmonious and vibrant canvas. This artwork invites the viewer to immerse themselves in a world of fantasies and interpretations, where each person can see something unique and feel a connection to nature and its endless motion.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (29, 'Fusion', 'c6.png', 'OIL ON CANVAS', '50 cm', 'The composition features images of leaves, flowers, and possibly marine creatures, interwoven in a smooth and organic manner. The color palette includes cool shades of blue, green, and purple, creating a sense of tranquility and harmony.', 'available', 700);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (30, 'Observer', 'd1.png', 'OIL ON CANVAS', '140 x 90 x 1 D cm', 'This painting represents a modern take on the classics, where the ancient ideal of beauty, symbolized by Michelangelo\'s statue of David, is intertwined with vibrant elements of contemporary art and abstraction. The figure of David, embodying timeless values of masculine strength and beauty, is set against a backdrop of dynamic strokes in bright, almost neon colors—green, blue, and purple—that break the monumentality of the sculpture, creating a contrast with the idealized body. The right side of the composition is filled with a profusion of flowers, where realistically rendered petals and leaves seem to reach into the space of the sculpture. This floral motif symbolizes life, growth, and the transience of nature, compared to the cold immobility of marble. The artwork establishes a dialogue between the past and the present: the timeless beauty of classical sculpture and the modern art movements, driven by experimentation, saturation, and rethinking of conventions. It invites viewers to reflect on how our perceptions of beauty and art continue to evolve.', 'available', 4000);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (31, 'Open', 'cl1.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting masterfully balances contrasts and symbolism. The artist draws attention to the golden hand, illuminated against a dark, abstract backdrop. The hand feels more than just a physical object — it suggests power, control, or inner strength. Its detailed, elegant lines, highlighted by light, sharply contrast with the blurred, abstract background, evoking tension and mystery.', 'sold', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (32, 'Hope', 'cl2.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting is filled with subtle symbolism and a sense of incompleteness. At the center of the composition is a golden hand, raised in a gesture that can be interpreted as a sign of approval, control, or inner harmony. The metallic texture of the hand gives it an artificial yet majestic quality, as if it were part of an ancient statue or artifact possessing special power.', 'in private collection', 0);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (33, 'Gate', 'cl3.jpg', 'OIL ON CANVAS', '40 X 50', 'This painting represents a combination of realism and abstraction. The central element of the composition is a hand extended forward, holding an unusual object that resembles a stylized pomegranate or flower. The hand is depicted in a highly realistic manner, with attention to light and shadow, emphasizing its three-dimensionality and texture. Surrounding the hand are abstract, broad brushstrokes in various shades of brown, beige, and black, creating a sense of movement and adding dynamism. These strokes give the painting a modern, expressive quality.', 'available', 1500);
INSERT INTO gallery (id, name, image, type, size, description, status, price) VALUES (34, 'Heritage', 'veil.jpg', 'OIL ON CANVAS', '155 х 105', 'Sit amet, consectetur adipiscing elit. Praesent at cursus magna, at dapibus eros. Aliquam tincidunt tortor eu placerat vehicula. Curabitur feugiat faucibus mauris id ullamcorper.', 'available', 7000);